task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../configs/dataset/LLVIP/train/
    ann_file: ../configs/dataset/LLVIP/instances_train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 0
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../configs/dataset/LLVIP/val/
    ann_file: ../configs/dataset/LLVIP/instances_val.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 2
  num_workers: 0
  drop_last: False